### ISSUE TITLE
I don't think there is a way to see the possible values for the settings file

### ISSUE THREAD

**Issue by AIP21** [adrisj7-AltoClef/altoclef#10]
I want to change the forceFieldStrategy option in the settings file but I don't know what other values for that to put in... Could you please make a file with a list of possible settings or something like that?
Thanks!

**Comment by adrisj7** [comment]
I have a comment in Settings.java, but here are the options:

FASTEST: All hostiles are attacked at every possible moment, every frame.
SMART: Closest hostile is attacked at max every 0.2 seconds.
OFF: Forcefield off

Will add this info officially either into the settings file itself or in a wiki of sorts.

**Comment by AIP21** [comment]
Awesome, thanks!

**Comment by Bluscream** [comment]
Where is it?
