### ISSUE TITLE
[Suggestion] Add a ETA

### ISSUE THREAD

**Issue by BlueBurgersTDD** [adrisj7-AltoClef/altoclef#13]

**Comment by adrisj7** [comment]
It would be nice, but probably not going to happen.

Let's say we're trying to get diamonds. Before getting an ETA for that I'd first need an ETA for:
- Getting an iron pick
    - Mining 3 iron ore
    - Smelting 3 iron ore
    - Getting a Stone Pick
        - Mining 3 stone
        - Getting planks etc.
        - etc.
    - Getting planks, if we don't have them already etc.
- Mining the diamonds.

That's possible. But even if I get those ETA's done, I have a bigger problem:
The "mine diamonds" task would need to know every child task it may run. At the moment, which sub-task is run is determined ENTIRELY in the tasks "tick" update function, and not in some easy-to-read data structure. So if you ask a task "Hey, what child tasks/subtasks will you run in the future?" it can't tell you. It can only tell you what it's running NOW.

Might represent a flaw in the system, not sure, but ATM this would be very difficult to do unfortunately.
