### ISSUE TITLE
Bot spams error after respawning while having mission to beat the game

### ISSUE THREAD

**Issue by BlueBurgersTDD** [adrisj7-AltoClef/altoclef#17]
This error occured yesterday, it might already be fixed. When the bot has gotten all required materials after respawning, it goes back to the end. If the end portal is not loaded, it spams a error many times per second until you stop the task manually.

![image](https://user-images.githubusercontent.com/58081413/119259645-7a55cd80-bbcf-11eb-8cdb-ca2641b21593.png)

**Comment by adrisj7** [comment]
Whoah, I never encountered this but this might be huge.

How can I replicate this? What state is the run/bot in now? I assume the end portal is filled and the bot respawns far away from the portal (so it's not loaded into a chunk), right?

**Comment by BlueBurgersTDD** [comment]
Yes thats's right

**Comment by BlueBurgersTDD** [comment]
You can replicate it by filling a portal, having the bed a few hundred blocks away, and killing the bot in the end. It will get all required materials, if the end portal never loaded, it will spam the error.

**Comment by BlueBurgersTDD** [comment]
I dont have much except the logs and some details because it happened yesterday, but that should be enough.

**Comment by adrisj7** [comment]
What's your render distance by the way, it's not under 12 by any chance?

**Comment by BlueBurgersTDD** [comment]
I'll record a video where I do it

**Comment by BlueBurgersTDD** [comment]
https://www.youtube.com/watch?v=i2lkVlRa9ME still processing, i didn't get this error, but i got another one!

**Comment by adrisj7** [comment]
Interesting! I think the low render distance is messing with it, "BeatMinecraft" isn't designed for that unfortunately. That's why you're getting stuck in the end, and it might be why there are so many mobs hoarding the bot, not sure why you can't move though.

The crafting issue I'm looking into right now, that feels weird.

**Comment by BlueBurgersTDD** [comment]
The first time the error occurred, I had 12 render distance

**Comment by adrisj7** [comment]
Unable to recreate and seems to be tied to render distance, closing for now until it resurfaces.
