### ISSUE TITLE
Bot doesn't de-equip item when sleeping in bed

### ISSUE THREAD

**Issue by adrisj7** [adrisj7-AltoClef/altoclef#20]
Issue:
If the bot is holding an eye of ender and is instructed to sleep in a bed, it will right click on the bed with an eye of ender and throw the eye.

What should happen:
Before right clicking to interact with anything, the bot should de-equip itself of any usable items (preferably bare handed if inventory not full)

Steps to recreate:
Equip eye of ender, then make bot sleep in bed/set spawn.

**Comment by solonovamax** [comment]
is there no way to send a USE packet for the bed, even with the eye of ender in  your hand?

**Comment by adrisj7** [comment]
At the moment, the bot rarely sends packets manually. Almost everything is handled through direct player controllers and right clicking on things. While probably less efficient, it's less prone to server protection issues and feels slightly more realistic (that's debatable, but it's how Baritone does things so that's how we'll do em)

**Comment by adrisj7** [comment]
I believe this was fixed on stream before the 9th run.
