### ISSUE TITLE
Migrate crafting tree to JSON or YAML files

### ISSUE THREAD

**Issue by solonovamax** [adrisj7-AltoClef/altoclef#23]
Currently, you have a massive class which constructs the tree of crafting recipes.
It would be MUCH nicer if that could instead just be a bunch of json files or smth.

Like `logs.json`, `food.json`, `end.json`, `nether.json`, `materials.json`, etc.

**Comment by solonovamax** [comment]
wait I just realized I'm stupid and this is a duplicate of #5 lol.
I made the issue myself and then forgot about it

**Comment by BlueBurgersTDD** [comment]
![3b5.jpg](https://user-images.githubusercontent.com/58081413/119333901-bbf77e80-bc8a-11eb-8196-c1a01e60772b.jpg)
