### ISSUE TITLE
@get enchanting_table fails crafting diamond pick

### ISSUE THREAD

**Issue by CodeF53** [adrisj7-AltoClef/altoclef#26]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/37855219/119294057-dab92f00-bc10-11eb-8bbe-e766a77c72f6.gif)

this issue does not occur when trying to craft a diamond pickaxe for `@get diamond_pickaxe`

**Comment by adrisj7** [comment]
Should be fixed with [Commit 9647deba4fdb5893a907e1d05f8e8daa2010eb65](https://github.com/adrisj7-AltoClef/altoclef/commit/9647deba4fdb5893a907e1d05f8e8daa2010eb65)
