### ISSUE TITLE
[Suggestion] Make a discord server for autoclef

### ISSUE THREAD

**Issue by BlueBurgersTDD** [adrisj7-AltoClef/altoclef#27]
I'm sure many people have had issues using/compiling this, but github issues is not the best way to get support as it's not something wrong with the code.

**Comment by solonovamax** [comment]
would also be nice to have somewhere where devs could talk

**Comment by adrisj7** [comment]
Your wish is my command https://discord.gg/thKuV2xj

Am new to this so feel free to test out the limits of permissions/give me advice

**Comment by adrisj7** [comment]
If that didn't work, try https://discord.gg/fUUEHeNmXb
