### ISSUE TITLE
Getting golden apples is broken

### ISSUE THREAD

**Issue by BlueBurgersTDD** [adrisj7-AltoClef/altoclef#9]
AltoClef cannot craft golden apples correctly. It tries to use iron nuggets, but you need golden ingots to make a golden apple.
![image](https://user-images.githubusercontent.com/58081413/119231981-ab78c400-bb23-11eb-8c6b-9831fff26e06.png)
![image](https://user-images.githubusercontent.com/58081413/119231995-be8b9400-bb23-11eb-932b-52e6fcfac07b.png)

**Comment by adrisj7** [comment]
Huh, guess they changed the recipe. Fixed with latest commit!
